[INFO]: Hi, This is root.
[INFO]: After the configurations are successfully processed and dirs are created.
[INFO]: The pipeline of the project will begin now.
2022/12/29 14:08:28	INFO	wandb	Watching
Traceback (most recent call last):
  File "/users/sista/kkontras/Documents/Sleep_Project/main_paper_2.py", line 62, in <module>
    main()
  File "/users/sista/kkontras/Documents/Sleep_Project/main_paper_2.py", line 58, in main
    agent.run()
  File "/users/sista/kkontras/Documents/Sleep_Project/agents/sleep_test/train_c_agent.py", line 173, in run
    self.mem_loader.sleep_load(self.config.model.save_dir)
  File "/users/sista/kkontras/Documents/Sleep_Project/agents/sleep_test/helpers/Loader.py", line 120, in sleep_load
    checkpoint = torch.load(file_name)
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/esat/smcdata/users/kkontras/Image_Dataset/no_backup/data/2021_data/shhs1/multi_modal/paper_models/fourier_transformer_eeg_eog_mat_BLIP_al01_shared_b16_freetrain_rpos_nopos_nonsharedpreds_drop03_align_inner_trial1_incomplete_100p_0e_200o.pth.tar'
